// Datos de los 5 casos piloto para el reproductor de escenarios (Fase A).
// Contenido bilingüe ES/EN. Cifras de KPI marcadas (estimación, T1) hasta el deep-research.
// Ver skill .claude/skills/crear-caso-de-uso para el modelo de datos.

export const stageN = [
  {es: 'Contexto', en: 'Context'},
  {es: 'Solución', en: 'Solution'},
  {es: 'Impacto', en: 'Impact'},
  {es: 'Riesgo', en: 'Risk'},
  {es: 'Remediación', en: 'Remediation'},
];

export const accents = ['var(--sp-info)', 'var(--sp-mcp)', 'var(--sp-purple)', 'var(--sp-red)', 'var(--sp-green)'];

export const kindLbl = {
  contexto: {es: 'contexto', en: 'context'},
  solucion: {es: 'solución', en: 'solution'},
  impacto: {es: 'impacto', en: 'impact'},
  block: {es: 'riesgo · bloqueado', en: 'risk · blocked'},
  pass: {es: 'remediación · permitido', en: 'remediation · allowed'},
};

// Layout compartido de nodos: id, kind, x, y, appearStage.
// Separación mínima >55px entre cajas en cualquier etapa (sin solapes).
export const LAYOUT = [
  {id: 'user', kind: 'user', x: 30, y: 172, ap: 0},
  {id: 'agent', kind: 'agent', x: 240, y: 172, ap: 0},
  {id: 'gw', kind: 'gw', x: 445, y: 172, ap: 4},
  {id: 'llm', kind: 'llm', x: 660, y: 52, ap: 1},
  {id: 'mcpA', kind: 'mcp', x: 785, y: 150, ap: 1},
  {id: 'mcpB', kind: 'mcp', x: 785, y: 240, ap: 1},
  {id: 'ext', kind: 'external', x: 785, y: 330, ap: 3},
  {id: 'shadow', kind: 'mcp', x: 240, y: 322, ap: 3},
  {id: 'trace', kind: 'trace', x: 470, y: 322, ap: 4},
  {id: 'registry', kind: 'registry', x: 40, y: 322, ap: 4},
];
export const NW = 150;
export const NH = 54;

// Coreografía compartida de las 5 etapas
export const STEP_META = [
  {stage: 0, kind: 'contexto', on: ['user'], edges: [['user', 'agent', 'base']]},
  {stage: 1, kind: 'solucion', on: ['user', 'agent', 'llm', 'mcpA', 'mcpB'], edges: [['user', 'agent', 'active'], ['agent', 'llm', 'active'], ['agent', 'mcpA', 'mcp'], ['agent', 'mcpB', 'mcp']], badge: 'id'},
  {stage: 2, kind: 'impacto', on: ['agent', 'llm', 'mcpA', 'mcpB'], edges: [['agent', 'llm', 'pass'], ['agent', 'mcpA', 'pass'], ['agent', 'mcpB', 'pass']]},
  {stage: 3, kind: 'block', on: ['agent', 'ext', 'shadow'], danger: ['agent', 'ext', 'shadow'], edges: [['agent', 'ext', 'adv'], ['agent', 'shadow', 'adv']], badge: 'risk'},
  {stage: 4, kind: 'pass', on: ['agent', 'mcpA', 'mcpB', 'gw', 'trace', 'registry'], gw: true, edges: [['agent', 'gw', 'active'], ['gw', 'mcpA', 'pass'], ['gw', 'mcpB', 'pass'], ['gw', 'trace', 'trace'], ['gw', 'ext', 'block'], ['registry', 'shadow', 'block']], hitl: true, badge: 'ok'},
];

export const UI = {
  es: {
    prod: 'Capacitación IA · casos de uso', prev: '← Anterior', next: 'Siguiente →', caseLbl: 'Caso',
    hitlAp: '✓ Aprobar', hitlDn: '✕ Denegar', detail: 'Ir al detalle', back: '↑ Volver al reproductor',
    hint: '▸ Este paso no requiere gate ni verificación de identidad',
    identQ: '¿Identidad del agente verificada?', identOk: 'SPIFFE + OIDC verificados', okCap: 'Identidad + política aplicadas',
    apOk: 'Aprobado · ejecutado · con traza', dnOk: 'Denegado · bloqueado', bloque: 'Bloque',
    awaiting: 'Esperando decisión humana', decideAgain: '↺ Volver a decidir',
    awaitingCap: 'La acción sensible queda retenida en el gate del agentgateway; requiere aprobación humana antes de ejecutarse.',
    approvedCap: 'Aprobado: la acción se ejecuta a través del gateway con identidad propia del agente y queda trazada.',
    deniedCap: 'Denegado: el gateway bloquea la acción; no se ejecuta y la decisión queda registrada.',
    kpiNote: '<b class="g">✓ Beneficio inmediato:</b> con solo adoptar IA agéntica y generativa ya estás obteniendo esta mejora de eficiencia. <b class="w">⚠ Pero no sale gratis:</b> esa ganancia <b>no es segura ni cumple la normativa</b> por sí sola. Sin la capa de gobierno (identidad del agente, control de MCP, guardarraíles y traza) del <b>Plan Director (Pieza 2)</b>, el mismo caso expone datos, incumple y descontrola el coste — ver los bloques de <b>Riesgo</b> y <b>Remediación</b>.',
    registryBand: 'inventario transversal de agentes y MCP en todo el entorno — lo no registrado (shadow-mcp) queda fuera: sin registro no hay identidad ni allowlist.',
  },
  en: {
    prod: 'AI training · use cases', prev: '← Previous', next: 'Next →', caseLbl: 'Case',
    hitlAp: '✓ Approve', hitlDn: '✕ Deny', detail: 'Go to detail', back: '↑ Back to the player',
    hint: '▸ This step needs no gate or identity check',
    identQ: 'Agent identity verified?', identOk: 'SPIFFE + OIDC verified', okCap: 'Identity + policy enforced',
    apOk: 'Approved · executed · traced', dnOk: 'Denied · blocked', bloque: 'Block',
    awaiting: 'Awaiting human decision', decideAgain: '↺ Decide again',
    awaitingCap: 'The sensitive action is held at the agentgateway gate; it needs human approval before it runs.',
    approvedCap: 'Approved: the action runs through the gateway with the agent’s own identity and is traced.',
    deniedCap: 'Denied: the gateway blocks the action; it does not run and the decision is logged.',
    kpiNote: '<b class="g">✓ Immediate benefit:</b> simply by adopting agentic and generative AI you are already getting this efficiency gain. <b class="w">⚠ But it is not free:</b> that gain is <b>neither secure nor compliant</b> on its own. Without the governance layer (agent identity, MCP control, guardrails and tracing) of the <b>Plan Director (Piece 2)</b>, the same case leaks data, breaches regulation and lets cost run — see the <b>Risk</b> and <b>Remediation</b> blocks.',
    registryBand: 'cross-cutting inventory of agents and MCPs across the whole environment — anything unregistered (shadow-mcp) stays out: no registration means no identity and no allowlist.',
  },
};

export const CASES = [
  {
    id: 'legal', role: {es: 'Legal', en: 'Legal'}, pat: {es: 'documentos', en: 'documents'}, gw: ['LLM Gateway', 'MCP Gateway'],
    title: {es: 'Revisión de contratos (redlining)', en: 'Contract review (redlining)'},
    scTitle: {es: 'Redlining gobernado', en: 'Governed redlining'}, scSub: {es: 'Abogado in-house · 100–300 contratos/año', en: 'In-house lawyer · 100–300 contracts/year'},
    n: {user: {l: {es: 'Abogado', en: 'Lawyer'}, s: {es: 'usuario', en: 'user'}}, agent: {l: 'redline-agent', s: {es: 'agente', en: 'agent'}}, llm: {s: {es: 'razona/redacta', en: 'reasons/drafts'}}, mcpA: {l: 'mcp-ironclad', s: 'contracts:read'}, mcpB: {l: 'mcp-sharepoint', s: 'templates:read'}, ext: {l: {es: 'endpoint externo', en: 'external endpoint'}, s: {es: 'no auditado', en: 'unaudited'}}, shadow: {s: {es: 'no registrado', en: 'unregistered'}}},
    risk: {es: 'Prompt injection + shadow-mcp', en: 'Prompt injection + shadow-mcp'},
    hitl: {es: '¿Aprobar la escritura del redline en la plantilla?', en: 'Approve writing the redline to the template?'},
    caps: [
      {es: 'Contexto: 100–300 contratos/año revisados a mano, cláusula a cláusula, buscando el precedente en correos.', en: 'Context: 100–300 contracts/year reviewed by hand, clause by clause, hunting precedent in email.'},
      {es: 'El agente lee plantilla y contrato vía MCP en lectura; el LLM propone el redline cláusula a cláusula.', en: 'The agent reads template and contract via read-only MCP; the LLM proposes the redline clause by clause.'},
      {es: 'Impacto: 3 h → 1 h por contrato; cláusulas materiales del 85% al 97%. ≈ 400 h/año.', en: 'Impact: 3 h → 1 h per contract; material clauses 85%→97%. ≈ 400 h/year.'},
      {es: 'Sin control: prompt injection desde el PDF, scope :write que firmaría solo, exfiltración y un shadow-mcp no registrado.', en: 'Ungoverned: prompt injection from the PDF, a :write scope that would sign, exfiltration and an unregistered shadow-mcp.'},
      {es: 'Con gobierno: agentgateway se interpone (identidad, allowlist MCP, PII, traza); Istio niega el egress; agentregistry deja fuera al shadow-mcp; la escritura pasa por aprobación humana.', en: 'Governed: agentgateway sits in path (identity, MCP allowlist, PII, trace); Istio denies egress; agentregistry keeps the shadow-mcp out; the write goes through human approval.'},
    ],
    comps: [
      {cn: 'agentgateway', cd: {es: 'LLM+MCP Gateway. Allowlist contracts:read, prompt guard con PII, rate limit por tokens, traza.', en: 'LLM+MCP Gateway. Allowlist contracts:read, prompt guard with PII, token rate limit, trace.'}},
      {cn: 'kagent', cd: {es: 'Identidad del redline-agent; OBO con el scope del abogado.', en: 'redline-agent identity; OBO with the lawyer scope.'}},
      {cn: 'agentregistry', cd: {es: 'El shadow-mcp no registrado no obtiene allowlist ni identidad.', en: 'Unregistered shadow-mcp gets no allowlist or identity.'}},
      {cn: 'Istio ambient', cd: {es: 'SPIFFE mTLS; AuthorizationPolicy niega el egress al endpoint externo.', en: 'SPIFFE mTLS; AuthorizationPolicy denies egress to the external endpoint.'}},
    ],
    blocks: [
      {h: {es: 'Caso de uso', en: 'Use case'}, body: {es: '<p>In-house legal compara cada contrato (NDA, MSA, DPA) contra una plantilla, marca desviaciones y propone redacción, dejando traza de la negociación. Hoy: lectura manual con track-changes y búsqueda del precedente en correos.</p>', en: '<p>In-house legal compares each contract (NDA, MSA, DPA) against a template, flags deviations and proposes wording, keeping the negotiation traceable. Today: manual reading with track-changes and precedent-hunting in email.</p>'}},
      {h: {es: 'Cómo resolverlo', en: 'How to solve it'}, body: {es: "<h4>Local</h4><p>Ollama + Llama 3.1 70B sobre PDF + plantilla. Prompt: comparar cláusula a cláusula, marcar desviación material, no inventar jurisprudencia.</p><h4>Copilot</h4><p>M365 Copilot sobre SharePoint, sensibilidad <code>Confidential/Legal</code>.</p><h4>Claude Code</h4><p>Repo con <code>AGENTS.md</code>: plantillas por tipo, umbrales, formato track-changes; sin permisos de envío.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-ironclad</td><td>contracts:read</td></tr><tr><td>mcp-sharepoint</td><td>templates:read</td></tr></table>", en: "<h4>Local</h4><p>Ollama + Llama 3.1 70B over PDF + template. Prompt: compare clause by clause, flag material deviations, don't invent case law.</p><h4>Copilot</h4><p>M365 Copilot over SharePoint, sensitivity <code>Confidential/Legal</code>.</p><h4>Claude Code</h4><p>Repo with <code>AGENTS.md</code>: templates by type, thresholds, track-changes; no send permissions.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-ironclad</td><td>contracts:read</td></tr><tr><td>mcp-sharepoint</td><td>templates:read</td></tr></table>"}},
      {h: {es: 'KPIs y mejora', en: 'KPIs & gain'}, body: {es: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>Con agente</th></tr><tr><td>Redlining/contrato</td><td>3 h</td><td>1 h</td></tr><tr><td>Cláusulas materiales</td><td>85%</td><td>97%</td></tr></table><p class='sp-est'>(3−1) h × 200/año = 400 h/año por abogado. (estimación, T1)</p>", en: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>With agent</th></tr><tr><td>Redlining/contract</td><td>3 h</td><td>1 h</td></tr><tr><td>Material clauses</td><td>85%</td><td>97%</td></tr></table><p class='sp-est'>(3−1) h × 200/yr = 400 h/yr per lawyer. (estimate, T1)</p>"}},
      {sh: true, h: {es: 'Vulnerabilidades y riesgos', en: 'Vulnerabilities & risks'}, body: {es: '<ul><li><em>"Si subo el MSA a un servicio público, pierdo el privilegio cliente-abogado."</em></li><li><em>"Si el modelo alucina jurisprudencia y se cita, sanción al despacho."</em></li><li><em>"Scope contracts:write → el agente firma sin gate humano."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"Un MCP no registrado que nadie inventarió opera sin identidad ni control."</em></p><div class="sp-warn">Se cubre con la gobernanza de la <b>Pieza 2</b>. Normativa: secreto profesional, GDPR/AEPD, EU AI Act.</div>', en: '<ul><li><em>"If I upload the MSA to a public service, I lose attorney-client privilege."</em></li><li><em>"If the model hallucinates case law and it is cited, the firm is sanctioned."</em></li><li><em>"contracts:write scope → the agent signs with no human gate."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"An unregistered MCP nobody inventoried runs with no identity or control."</em></p><div class="sp-warn">Covered by the governance in <b>Piece 2</b>. Regulation: legal privilege, GDPR/AEPD, EU AI Act.</div>'}},
      {h: {es: 'Remediación (Solo.io)', en: 'Remediation (Solo.io)'}, body: {es: "<table class='sp-t'><tr><th>Riesgo</th><th>Componente</th><th>Mecanismo</th></tr><tr><td>Prompt injection</td><td class='sp-c'>agentgateway</td><td>prompt guard antes del LLM</td></tr><tr><td>Scope :write</td><td class='sp-c'>agentgateway+kagent</td><td>allowlist MCP solo :read</td></tr><tr><td>Exfiltración</td><td class='sp-c'>Istio</td><td>AuthorizationPolicy niega egress</td></tr><tr><td>Shadow AI</td><td class='sp-c'>agentregistry</td><td>sin registro no hay allowlist</td></tr></table><h4>Identidad</h4><p>SPIFFE mTLS + OIDC/JWT + OBO.</p><h4>Políticas</h4><p><code>AgentgatewayPolicy</code> (plano de datos) + <code>AuthorizationPolicy</code> (L4/L7).</p>", en: "<table class='sp-t'><tr><th>Risk</th><th>Component</th><th>Mechanism</th></tr><tr><td>Prompt injection</td><td class='sp-c'>agentgateway</td><td>prompt guard before the LLM</td></tr><tr><td>:write scope</td><td class='sp-c'>agentgateway+kagent</td><td>MCP allowlist read-only</td></tr><tr><td>Exfiltration</td><td class='sp-c'>Istio</td><td>AuthorizationPolicy denies egress</td></tr><tr><td>Shadow AI</td><td class='sp-c'>agentregistry</td><td>no registration, no allowlist</td></tr></table><h4>Identity</h4><p>SPIFFE mTLS + OIDC/JWT + OBO.</p><h4>Policies</h4><p><code>AgentgatewayPolicy</code> (data plane) + <code>AuthorizationPolicy</code> (L4/L7).</p>"}},
    ],
  },
  {
    id: 'finanzas', role: {es: 'Finanzas', en: 'Finance'}, pat: {es: 'analítico', en: 'analytical'}, gw: ['LLM Gateway', 'MCP Gateway'],
    title: {es: 'Análisis de varianza P&L', en: 'P&L variance analysis'},
    scTitle: {es: 'Varianza gobernada', en: 'Governed variance'}, scSub: {es: 'Analista FP&A · cierre mensual', en: 'FP&A analyst · monthly close'},
    n: {user: {l: {es: 'Analista', en: 'Analyst'}, s: {es: 'usuario', en: 'user'}}, agent: {l: 'fpna-agent', s: {es: 'agente', en: 'agent'}}, llm: {s: {es: 'redacta narrativa', en: 'drafts narrative'}}, mcpA: {l: 'mcp-erp', s: 'ledger:read'}, mcpB: {l: 'mcp-bi', s: 'warehouse:read'}, ext: {l: {es: 'endpoint externo', en: 'external endpoint'}, s: {es: 'no auditado', en: 'unaudited'}}, shadow: {s: {es: 'conector no reg.', en: 'unregistered conn.'}}},
    risk: {es: 'MNPI + conector shadow', en: 'MNPI + shadow connector'},
    hitl: {es: '¿Aprobar la publicación del comentario de cierre?', en: 'Approve publishing the close commentary?'},
    caps: [
      {es: 'Contexto: cada cierre el analista explica desviaciones presupuesto vs. real; horas en Excel cruzando cuentas.', en: 'Context: each close the analyst explains budget-vs-actual variances; hours in Excel cross-checking accounts.'},
      {es: 'El agente lee el ERP y el warehouse vía MCP en lectura y el LLM redacta la narrativa de varianza por cuenta.', en: 'The agent reads the ERP and warehouse via read-only MCP and the LLM drafts the per-account variance narrative.'},
      {es: 'Impacto: comentario de cierre 6 h → 2 h; mayor cobertura de cuentas y menos errores de atribución.', en: 'Impact: close commentary 6 h → 2 h; broader account coverage and fewer attribution errors.'},
      {es: 'Sin control: cifras no publicadas (MNPI) a un servicio público, scope :write al ledger, y un conector BI no registrado (shadow AI).', en: 'Ungoverned: non-public numbers (MNPI) to a public service, a :write scope on the ledger, and an unregistered BI connector (shadow AI).'},
      {es: 'Con gobierno: agentgateway (allowlist ledger:read, DLP, presupuesto de tokens, traza); Istio niega el egress; agentregistry bloquea el conector no registrado; publicar exige aprobación humana.', en: 'Governed: agentgateway (allowlist ledger:read, DLP, token budget, trace); Istio denies egress; agentregistry blocks the unregistered connector; publishing requires human approval.'},
    ],
    comps: [
      {cn: 'agentgateway', cd: {es: 'LLM+MCP Gateway. Allowlist ledger:read, DLP de cifras, presupuesto de tokens.', en: 'LLM+MCP Gateway. Allowlist ledger:read, figures DLP, token budget.'}},
      {cn: 'kagent', cd: {es: 'Identidad del fpna-agent; OBO con el rol del analista (segregación de funciones).', en: 'fpna-agent identity; OBO with the analyst role (segregation of duties).'}},
      {cn: 'agentregistry', cd: {es: 'El conector BI no registrado queda fuera del inventario y de la allowlist.', en: 'The unregistered BI connector stays out of inventory and allowlist.'}},
      {cn: 'Istio ambient', cd: {es: 'SPIFFE mTLS; niega el egress de datos financieros al exterior.', en: 'SPIFFE mTLS; denies egress of financial data.'}},
    ],
    blocks: [
      {h: {es: 'Caso de uso', en: 'Use case'}, body: {es: '<p>En cada cierre, FP&A explica por qué el real se desvía del presupuesto: cruzar cuentas del ERP con el warehouse, atribuir la desviación y redactar el comentario para dirección. Trabajo repetitivo y con plazo.</p>', en: '<p>Each close, FP&A explains why actuals deviate from budget: cross ERP accounts with the warehouse, attribute the variance and draft the commentary for management. Repetitive and deadline-bound.</p>'}},
      {h: {es: 'Cómo resolverlo', en: 'How to solve it'}, body: {es: "<h4>Local</h4><p>Modelo local sobre extractos anonimizados; prompt: atribuir varianza por cuenta y driver, citar la fuente, no rellenar huecos.</p><h4>Copilot</h4><p>Copilot en Excel/Fabric sobre el modelo financiero, etiqueta <code>Confidential/Finance</code>.</p><h4>Claude Code</h4><p><code>AGENTS.md</code> con plan de cuentas, umbral de materialidad y formato del comentario.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-erp</td><td>ledger:read</td></tr><tr><td>mcp-bi</td><td>warehouse:read</td></tr></table>", en: "<h4>Local</h4><p>Local model over anonymized extracts; prompt: attribute variance by account and driver, cite the source, don't fill gaps.</p><h4>Copilot</h4><p>Copilot in Excel/Fabric over the financial model, label <code>Confidential/Finance</code>.</p><h4>Claude Code</h4><p><code>AGENTS.md</code> with chart of accounts, materiality threshold and commentary format.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-erp</td><td>ledger:read</td></tr><tr><td>mcp-bi</td><td>warehouse:read</td></tr></table>"}},
      {h: {es: 'KPIs y mejora', en: 'KPIs & gain'}, body: {es: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>Con agente</th></tr><tr><td>Comentario de cierre</td><td>6 h</td><td>2 h</td></tr><tr><td>Cobertura de cuentas</td><td>60%</td><td>95%</td></tr></table><p class='sp-est'>4 h × 12 cierres = 48 h/año por analista. (estimación, T1)</p>", en: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>With agent</th></tr><tr><td>Close commentary</td><td>6 h</td><td>2 h</td></tr><tr><td>Account coverage</td><td>60%</td><td>95%</td></tr></table><p class='sp-est'>4 h × 12 closes = 48 h/yr per analyst. (estimate, T1)</p>"}},
      {sh: true, h: {es: 'Vulnerabilidades y riesgos', en: 'Vulnerabilities & risks'}, body: {es: '<ul><li><em>"Si pego cifras no publicadas en un chatbot público, expongo MNPI (MAR/CNMV, SOX)."</em></li><li><em>"Scope :write al ledger → el agente asienta un ajuste sin control."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"Un conector de BI que instalé por mi cuenta lee el warehouse sin que nadie lo sepa."</em></p><div class="sp-warn">Se cubre con la <b>Pieza 2</b>. Normativa: MAR/CNMV, SOX, GDPR.</div>', en: '<ul><li><em>"If I paste non-public numbers into a public chatbot, I expose MNPI (MAR, SOX)."</em></li><li><em>":write scope on the ledger → the agent posts an adjustment uncontrolled."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"A BI connector I installed myself reads the warehouse and nobody knows."</em></p><div class="sp-warn">Covered by <b>Piece 2</b>. Regulation: MAR, SOX, GDPR.</div>'}},
      {h: {es: 'Remediación (Solo.io)', en: 'Remediation (Solo.io)'}, body: {es: "<table class='sp-t'><tr><th>Riesgo</th><th>Componente</th><th>Mecanismo</th></tr><tr><td>MNPI a exterior</td><td class='sp-c'>agentgateway+Istio</td><td>DLP + AuthorizationPolicy niega egress</td></tr><tr><td>Escritura al ledger</td><td class='sp-c'>agentgateway+kagent</td><td>allowlist ledger:read; SoD por OBO</td></tr><tr><td>Shadow connector</td><td class='sp-c'>agentregistry</td><td>inventario obligatorio</td></tr></table><h4>Identidad</h4><p>SPIFFE + OIDC + OBO con el rol del analista.</p><h4>Políticas</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code>.</p>", en: "<table class='sp-t'><tr><th>Risk</th><th>Component</th><th>Mechanism</th></tr><tr><td>MNPI egress</td><td class='sp-c'>agentgateway+Istio</td><td>DLP + AuthorizationPolicy denies egress</td></tr><tr><td>Ledger write</td><td class='sp-c'>agentgateway+kagent</td><td>allowlist ledger:read; SoD via OBO</td></tr><tr><td>Shadow connector</td><td class='sp-c'>agentregistry</td><td>mandatory inventory</td></tr></table><h4>Identity</h4><p>SPIFFE + OIDC + OBO with the analyst role.</p><h4>Policies</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code>.</p>"}},
    ],
  },
  {
    id: 'soc', role: {es: 'IT / Seguridad', en: 'IT / Security'}, pat: {es: 'triage', en: 'triage'}, gw: ['MCP Gateway', 'AgentGateway'],
    title: {es: 'Triage de alertas del SOC', en: 'SOC alert triage'},
    scTitle: {es: 'Triage gobernado', en: 'Governed triage'}, scSub: {es: 'Analista SOC · miles de alertas/día', en: 'SOC analyst · thousands of alerts/day'},
    n: {user: {l: {es: 'Analista SOC', en: 'SOC analyst'}, s: {es: 'usuario', en: 'user'}}, agent: {l: 'triage-agent', s: {es: 'agente', en: 'agent'}}, llm: {s: {es: 'clasifica', en: 'classifies'}}, mcpA: {l: 'mcp-siem', s: 'events:read'}, mcpB: {l: 'mcp-edr', s: 'detections:read'}, ext: {l: {es: 'endpoint externo', en: 'external endpoint'}, s: {es: 'no auditado', en: 'unaudited'}}, shadow: {s: {es: 'agente no reg.', en: 'unregistered agent'}}},
    risk: {es: 'Prompt injection en logs + agente shadow', en: 'Log prompt injection + shadow agent'},
    hitl: {es: '¿Aprobar el aislamiento del host afectado?', en: 'Approve isolating the affected host?'},
    caps: [
      {es: 'Contexto: el SOC recibe miles de alertas; L1 se satura y los falsos positivos entierran lo importante.', en: 'Context: the SOC gets thousands of alerts; L1 is swamped and false positives bury what matters.'},
      {es: 'El agente lee SIEM y EDR vía MCP en lectura, clasifica por severidad (P0–P2) y propone acción; nada se ejecuta solo.', en: 'The agent reads SIEM and EDR via read-only MCP, classifies by severity (P0–P2) and proposes action; nothing runs on its own.'},
      {es: 'Impacto: triage por alerta 15 min → 3 min; menos falsos positivos escalados; MTTA más bajo.', en: 'Impact: triage per alert 15 min → 3 min; fewer escalated false positives; lower MTTA.'},
      {es: 'Sin control: una acción de contención automatizada aísla un host productivo, prompt injection oculto en un log, y un agente no inventariado con credenciales (shadow AI).', en: 'Ungoverned: an automated containment isolates a production host, prompt injection hidden in a log, and an uninventoried agent with credentials (shadow AI).'},
      {es: 'Con gobierno: agentgateway (MCP allowlist read-only, prompt guard sobre el contenido del log, traza); Istio niega el egress; agentregistry detecta y deja fuera al agente shadow; contener exige aprobación humana.', en: 'Governed: agentgateway (read-only MCP allowlist, prompt guard over log content, trace); Istio denies egress; agentregistry detects and excludes the shadow agent; containment requires human approval.'},
    ],
    comps: [
      {cn: 'agentgateway', cd: {es: 'MCP Gateway. Allowlist :read sobre SIEM/EDR, prompt guard del contenido de alertas, traza.', en: 'MCP Gateway. :read allowlist over SIEM/EDR, prompt guard on alert content, trace.'}},
      {cn: 'kagent', cd: {es: 'Identidad del triage-agent; access policies; OBO.', en: 'triage-agent identity; access policies; OBO.'}},
      {cn: 'agentregistry', cd: {es: 'Inventario de agentes/MCP: el agente no registrado no obtiene identidad.', en: 'Agent/MCP inventory: the unregistered agent gets no identity.'}},
      {cn: 'Istio ambient', cd: {es: 'SPIFFE mTLS; segmentación; niega el egress de logs.', en: 'SPIFFE mTLS; segmentation; denies log egress.'}},
    ],
    blocks: [
      {h: {es: 'Caso de uso', en: 'Use case'}, body: {es: '<p>El SOC vive sepultado en alertas. El L1 dedica el turno a descartar ruido; lo grave llega tarde. Se busca un primer filtro que clasifique por severidad y prepare el contexto, dejando la decisión al analista.</p>', en: '<p>The SOC is buried in alerts. L1 spends the shift dismissing noise; the serious stuff arrives late. The goal is a first filter that classifies by severity and prepares context, leaving the decision to the analyst.</p>'}},
      {h: {es: 'Cómo resolverlo', en: 'How to solve it'}, body: {es: "<h4>Local</h4><p>Modelo local sobre muestras de alertas anonimizadas; prompt: clasificar P0–P2, listar IOCs, proponer siguiente paso, no ejecutar.</p><h4>Copilot</h4><p>Copilot for Security sobre el tenant, sin acciones de escritura.</p><h4>Claude Code</h4><p><code>AGENTS.md</code> con playbooks de severidad y formato del ticket; solo lectura.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-siem</td><td>events:read</td></tr><tr><td>mcp-edr</td><td>detections:read</td></tr></table>", en: "<h4>Local</h4><p>Local model over anonymized alert samples; prompt: classify P0–P2, list IOCs, propose next step, don't execute.</p><h4>Copilot</h4><p>Copilot for Security over the tenant, no write actions.</p><h4>Claude Code</h4><p><code>AGENTS.md</code> with severity playbooks and ticket format; read-only.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-siem</td><td>events:read</td></tr><tr><td>mcp-edr</td><td>detections:read</td></tr></table>"}},
      {h: {es: 'KPIs y mejora', en: 'KPIs & gain'}, body: {es: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>Con agente</th></tr><tr><td>Triage por alerta</td><td>15 min</td><td>3 min</td></tr><tr><td>Falsos positivos escalados</td><td>40%</td><td>12%</td></tr></table><p class='sp-est'>12 min × 60 alertas/turno = 12 h/turno evitado. (estimación, T1)</p>", en: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>With agent</th></tr><tr><td>Triage per alert</td><td>15 min</td><td>3 min</td></tr><tr><td>Escalated false positives</td><td>40%</td><td>12%</td></tr></table><p class='sp-est'>12 min × 60 alerts/shift = 12 h/shift avoided. (estimate, T1)</p>"}},
      {sh: true, h: {es: 'Vulnerabilidades y riesgos', en: 'Vulnerabilities & risks'}, body: {es: '<ul><li><em>"Si el agente puede contener solo, aísla un host productivo por un falso positivo."</em></li><li><em>"Un log manipulado inyecta instrucciones al agente (prompt injection)."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"Un agente que un compañero desplegó con credenciales del SIEM opera sin que el SOC lo tenga inventariado — y podría ser el propio incidente."</em></p><div class="sp-warn">Se cubre con la <b>Pieza 2</b>. Normativa: NIS2, DORA, ISO 27001, GDPR.</div>', en: '<ul><li><em>"If the agent can contain on its own, it isolates a production host over a false positive."</em></li><li><em>"A tampered log injects instructions into the agent (prompt injection)."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"An agent a colleague deployed with SIEM credentials runs uninventoried by the SOC — and could be the incident itself."</em></p><div class="sp-warn">Covered by <b>Piece 2</b>. Regulation: NIS2, DORA, ISO 27001, GDPR.</div>'}},
      {h: {es: 'Remediación (Solo.io)', en: 'Remediation (Solo.io)'}, body: {es: "<table class='sp-t'><tr><th>Riesgo</th><th>Componente</th><th>Mecanismo</th></tr><tr><td>Contención automática</td><td class='sp-c'>agentgateway+HITL</td><td>allowlist :read; contener pasa por gate</td></tr><tr><td>Injection en log</td><td class='sp-c'>agentgateway</td><td>prompt guard sobre el contenido</td></tr><tr><td>Agente shadow</td><td class='sp-c'>agentregistry</td><td>inventario; sin registro no hay identidad</td></tr></table><h4>Identidad</h4><p>SPIFFE + OIDC + OBO.</p><h4>Políticas</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code> (L4/L7).</p>", en: "<table class='sp-t'><tr><th>Risk</th><th>Component</th><th>Mechanism</th></tr><tr><td>Auto containment</td><td class='sp-c'>agentgateway+HITL</td><td>:read allowlist; containment via gate</td></tr><tr><td>Log injection</td><td class='sp-c'>agentgateway</td><td>prompt guard over content</td></tr><tr><td>Shadow agent</td><td class='sp-c'>agentregistry</td><td>inventory; no registration no identity</td></tr></table><h4>Identity</h4><p>SPIFFE + OIDC + OBO.</p><h4>Policies</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code> (L4/L7).</p>"}},
    ],
  },
  {
    id: 'ops', role: {es: 'Operador (SRE)', en: 'Ops (SRE)'}, pat: {es: 'operacional', en: 'operational'}, gw: ['MCP Gateway', 'AgentGateway'],
    title: {es: 'Diagnóstico de incidente (read-only)', en: 'Incident diagnosis (read-only)'},
    scTitle: {es: 'Diagnóstico gobernado', en: 'Governed diagnosis'}, scSub: {es: 'SRE de guardia · incidente en curso', en: 'On-call SRE · live incident'},
    n: {user: {l: 'SRE', s: {es: 'usuario', en: 'user'}}, agent: {l: 'diag-agent', s: {es: 'agente', en: 'agent'}}, llm: {s: {es: 'correlaciona', en: 'correlates'}}, mcpA: {l: 'mcp-metrics', s: 'prometheus:read'}, mcpB: {l: 'mcp-logs', s: 'loki:read'}, ext: {l: {es: 'endpoint externo', en: 'external endpoint'}, s: {es: 'no auditado', en: 'unaudited'}}, shadow: {s: {es: 'script no reg.', en: 'unregistered script'}}},
    risk: {es: 'Acción de escritura + script shadow', en: 'Write action + shadow script'},
    hitl: {es: '¿Aprobar el rollback del despliegue afectado?', en: 'Approve rolling back the affected deploy?'},
    caps: [
      {es: 'Contexto: el SRE de guardia diagnostica bajo presión, correlacionando métricas, logs y trazas de varios sistemas.', en: 'Context: the on-call SRE diagnoses under pressure, correlating metrics, logs and traces across systems.'},
      {es: 'El agente lee la observabilidad vía MCP en lectura, correlaciona señales y propone hipótesis y runbook; no ejecuta cambios.', en: 'The agent reads observability via read-only MCP, correlates signals and proposes hypotheses and a runbook; it makes no changes.'},
      {es: 'Impacto: MTTR más bajo; tiempo de diagnóstico 40 min → 12 min; mejor hipótesis inicial.', en: 'Impact: lower MTTR; diagnosis time 40 min → 12 min; better initial hypothesis.'},
      {es: 'Sin control: una herramienta de escritura (restart/scale/rollback) actúa sin gate, prompt injection desde un log, y un script con kubeconfig que nadie registró (shadow AI).', en: 'Ungoverned: a write tool (restart/scale/rollback) acts with no gate, prompt injection from a log, and a script with kubeconfig nobody registered (shadow AI).'},
      {es: 'Con gobierno: agentgateway (allowlist :read, bloqueo de tools de escritura, traza); Istio segmenta y niega el egress; agentregistry deja fuera al script; toda acción mutante pasa por aprobación humana.', en: 'Governed: agentgateway (:read allowlist, write-tool block, trace); Istio segments and denies egress; agentregistry excludes the script; every mutating action goes through human approval.'},
    ],
    comps: [
      {cn: 'agentgateway', cd: {es: 'MCP Gateway. Allowlist :read, bloquea tools de escritura, traza por invocación.', en: 'MCP Gateway. :read allowlist, blocks write tools, per-invocation trace.'}},
      {cn: 'kagent', cd: {es: 'Identidad del diag-agent; HITL en pausa/reanudar de tareas (A2A).', en: 'diag-agent identity; HITL on task pause/resume (A2A).'}},
      {cn: 'agentregistry', cd: {es: 'El script con kubeconfig no registrado no obtiene identidad ni allowlist.', en: 'The unregistered kubeconfig script gets no identity or allowlist.'}},
      {cn: 'Istio ambient', cd: {es: 'SPIFFE mTLS; segmentación por namespace; niega egress.', en: 'SPIFFE mTLS; per-namespace segmentation; denies egress.'}},
    ],
    blocks: [
      {h: {es: 'Caso de uso', en: 'Use case'}, body: {es: '<p>En un incidente, el SRE pierde minutos saltando entre Grafana, logs y trazas para formar una hipótesis. Un agente que reúna y correlacione las señales acelera el diagnóstico sin tocar producción.</p>', en: '<p>During an incident the SRE loses minutes hopping between Grafana, logs and traces to form a hypothesis. An agent that gathers and correlates the signals speeds diagnosis without touching production.</p>'}},
      {h: {es: 'Cómo resolverlo', en: 'How to solve it'}, body: {es: "<h4>Local</h4><p>Modelo local sobre exportes de métricas/logs; prompt: correlacionar por ventana temporal, proponer causa probable y runbook, no ejecutar.</p><h4>Copilot</h4><p>Asistente del proveedor de observabilidad en modo lectura.</p><h4>Claude Code</h4><p><code>AGENTS.md</code> con topología de servicios, SLOs y runbooks; sin credenciales de escritura.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-metrics</td><td>prometheus:read</td></tr><tr><td>mcp-logs</td><td>loki:read</td></tr></table>", en: "<h4>Local</h4><p>Local model over metric/log exports; prompt: correlate by time window, propose likely cause and runbook, don't execute.</p><h4>Copilot</h4><p>Observability vendor assistant in read mode.</p><h4>Claude Code</h4><p><code>AGENTS.md</code> with service topology, SLOs and runbooks; no write credentials.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-metrics</td><td>prometheus:read</td></tr><tr><td>mcp-logs</td><td>loki:read</td></tr></table>"}},
      {h: {es: 'KPIs y mejora', en: 'KPIs & gain'}, body: {es: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>Con agente</th></tr><tr><td>Tiempo de diagnóstico</td><td>40 min</td><td>12 min</td></tr><tr><td>Hipótesis inicial correcta</td><td>55%</td><td>80%</td></tr></table><p class='sp-est'>28 min × incidentes/mes → menor MTTR. (estimación, T1)</p>", en: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>With agent</th></tr><tr><td>Diagnosis time</td><td>40 min</td><td>12 min</td></tr><tr><td>Correct initial hypothesis</td><td>55%</td><td>80%</td></tr></table><p class='sp-est'>28 min × incidents/month → lower MTTR. (estimate, T1)</p>"}},
      {sh: true, h: {es: 'Vulnerabilidades y riesgos', en: 'Vulnerabilities & risks'}, body: {es: '<ul><li><em>"Si el agente tiene una tool de escritura, hace rollback en producción sin gate."</em></li><li><em>"Un log con payload malicioso redirige al agente (prompt injection)."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"Un script con kubeconfig que dejé corriendo actúa sobre el clúster y no está inventariado."</em></p><div class="sp-warn">Se cubre con la <b>Pieza 2</b>. Normativa: NIS2/DORA (si es servicio crítico), ISO 27001.</div>', en: '<ul><li><em>"If the agent has a write tool, it rolls back production with no gate."</em></li><li><em>"A log with a malicious payload redirects the agent (prompt injection)."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"A script with kubeconfig I left running acts on the cluster and is not inventoried."</em></p><div class="sp-warn">Covered by <b>Piece 2</b>. Regulation: NIS2/DORA (if critical), ISO 27001.</div>'}},
      {h: {es: 'Remediación (Solo.io)', en: 'Remediation (Solo.io)'}, body: {es: "<table class='sp-t'><tr><th>Riesgo</th><th>Componente</th><th>Mecanismo</th></tr><tr><td>Escritura sin gate</td><td class='sp-c'>agentgateway+kagent</td><td>allowlist :read; mutación por HITL (A2A)</td></tr><tr><td>Injection en log</td><td class='sp-c'>agentgateway</td><td>prompt guard sobre el contenido</td></tr><tr><td>Script shadow</td><td class='sp-c'>agentregistry</td><td>inventario obligatorio</td></tr></table><h4>Identidad</h4><p>SPIFFE + OIDC + OBO.</p><h4>Políticas</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code> por namespace.</p>", en: "<table class='sp-t'><tr><th>Risk</th><th>Component</th><th>Mechanism</th></tr><tr><td>Ungated write</td><td class='sp-c'>agentgateway+kagent</td><td>:read allowlist; mutation via HITL (A2A)</td></tr><tr><td>Log injection</td><td class='sp-c'>agentgateway</td><td>prompt guard over content</td></tr><tr><td>Shadow script</td><td class='sp-c'>agentregistry</td><td>mandatory inventory</td></tr></table><h4>Identity</h4><p>SPIFFE + OIDC + OBO.</p><h4>Policies</h4><p><code>AgentgatewayPolicy</code> + per-namespace <code>AuthorizationPolicy</code>.</p>"}},
    ],
  },
  {
    id: 'banca', role: {es: 'Frontline · banca', en: 'Frontline · banking'}, pat: {es: 'asistencia', en: 'assistance'}, gw: ['LLM Gateway', 'MCP Gateway'],
    title: {es: 'Asistente al puesto en oficina', en: 'Branch desk assistant'},
    scTitle: {es: 'Asistente gobernado', en: 'Governed assistant'}, scSub: {es: 'Empleado de oficina · atención en ventanilla', en: 'Branch employee · counter service'},
    n: {user: {l: {es: 'Empleado', en: 'Employee'}, s: {es: 'oficina', en: 'branch'}}, agent: {l: 'branch-assist', s: {es: 'agente', en: 'agent'}}, llm: {s: {es: 'responde', en: 'answers'}}, mcpA: {l: 'mcp-kb', s: 'policies:read'}, mcpB: {l: 'mcp-core', s: 'customer:read•mask'}, ext: {l: {es: 'móvil personal', en: 'personal phone'}, s: {es: 'WhatsApp', en: 'WhatsApp'}}, shadow: {s: {es: 'app no aprobada', en: 'unapproved app'}}},
    risk: {es: 'Asesoramiento sin gate + app shadow', en: 'Ungated advice + shadow app'},
    hitl: {es: '¿Derivar a un asesor humano (producto de inversión)?', en: 'Hand off to a human advisor (investment product)?'},
    caps: [
      {es: 'Contexto: el empleado atiende en ventanilla y necesita datos de producto y procedimiento correctos y rápidos.', en: 'Context: the employee serves at the counter and needs correct, fast product and procedure information.'},
      {es: 'Un asistente aprobado responde con la base de conocimiento de producto/políticas vía MCP en lectura, con datos de cliente enmascarados; no da asesoramiento de inversión.', en: 'An approved assistant answers from the product/policy knowledge base via read-only MCP, with masked customer data; it gives no investment advice.'},
      {es: 'Impacto: tiempo de resolución en ventanilla 8 min → 3 min; mayor precisión de respuesta; CSAT arriba.', en: 'Impact: counter resolution 8 min → 3 min; higher answer accuracy; CSAT up.'},
      {es: 'Sin control: dar asesoramiento de inversión sin gate (MiFID II), datos de cliente sin enmascarar, uso desde móvil personal/WhatsApp y una app no aprobada (shadow AI).', en: 'Ungoverned: giving investment advice with no gate (MiFID II), unmasked customer data, use from a personal phone/WhatsApp and an unapproved app (shadow AI).'},
      {es: 'Con gobierno: agentgateway (allowlist KB read, enmascarado de PII del core, disclosure, traza); Istio niega el egress; agentregistry bloquea la app no aprobada; el asesoramiento se deriva a un humano.', en: 'Governed: agentgateway (KB read allowlist, core PII masking, disclosure, trace); Istio denies egress; agentregistry blocks the unapproved app; advice is handed off to a human.'},
    ],
    comps: [
      {cn: 'agentgateway', cd: {es: 'LLM+MCP Gateway. Enmascarado de PII del core, allowlist KB read, disclosure, traza.', en: 'LLM+MCP Gateway. Core PII masking, KB read allowlist, disclosure, trace.'}},
      {cn: 'kagent', cd: {es: 'Identidad del branch-assist; OBO con el rol del empleado.', en: 'branch-assist identity; OBO with the employee role.'}},
      {cn: 'agentregistry', cd: {es: 'La app no aprobada no se registra: sin identidad ni acceso.', en: 'The unapproved app is not registered: no identity, no access.'}},
      {cn: 'Istio ambient', cd: {es: 'SPIFFE mTLS; niega el egress de datos de cliente.', en: 'SPIFFE mTLS; denies egress of customer data.'}},
    ],
    blocks: [
      {h: {es: 'Caso de uso', en: 'Use case'}, body: {es: '<p>En ventanilla, el empleado necesita responder con exactitud sobre productos, comisiones y procedimientos, sin hacer esperar al cliente ni improvisar condiciones. Un asistente aprobado consulta la fuente oficial y resume.</p>', en: '<p>At the counter, the employee must answer accurately about products, fees and procedures without keeping the customer waiting or improvising terms. An approved assistant queries the official source and summarizes.</p>'}},
      {h: {es: 'Cómo resolverlo', en: 'How to solve it'}, body: {es: "<h4>Local</h4><p>No aplica en el puesto: usar solo la <b>herramienta aprobada por la entidad</b>. Nada de modelos personales.</p><h4>Copilot</h4><p>Copilot corporativo restringido a la KB de producto; sin datos de cliente salvo enmascarados.</p><h4>App del puesto</h4><p>Asistente con <code>AGENTS.md</code> de producto/procedimiento; respuestas con cita a la política.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-kb</td><td>policies:read</td></tr><tr><td>mcp-core</td><td>customer:read (masked)</td></tr></table>", en: "<h4>Local</h4><p>Not at the desk: use only the <b>bank-approved tool</b>. No personal models.</p><h4>Copilot</h4><p>Corporate Copilot restricted to the product KB; no customer data unless masked.</p><h4>Desk app</h4><p>Assistant with a product/procedure <code>AGENTS.md</code>; answers cite the policy.</p><h4>MCPs</h4><table class='sp-t'><tr><th>MCP</th><th>Scopes</th></tr><tr><td>mcp-kb</td><td>policies:read</td></tr><tr><td>mcp-core</td><td>customer:read (masked)</td></tr></table>"}},
      {h: {es: 'KPIs y mejora', en: 'KPIs & gain'}, body: {es: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>Con agente</th></tr><tr><td>Resolución en ventanilla</td><td>8 min</td><td>3 min</td></tr><tr><td>Precisión de respuesta</td><td>82%</td><td>96%</td></tr></table><p class='sp-est'>5 min × consultas/día × empleados. (estimación, T1)</p>", en: "<table class='sp-t'><tr><th>KPI</th><th>Base</th><th>With agent</th></tr><tr><td>Counter resolution</td><td>8 min</td><td>3 min</td></tr><tr><td>Answer accuracy</td><td>82%</td><td>96%</td></tr></table><p class='sp-est'>5 min × queries/day × employees. (estimate, T1)</p>"}},
      {sh: true, h: {es: 'Vulnerabilidades y riesgos', en: 'Vulnerabilities & risks'}, body: {es: '<ul><li><em>"Si el asistente recomienda un producto de inversión, doy asesoramiento sin idoneidad (MiFID II)."</em></li><li><em>"Si consulto datos de cliente sin enmascarar, incumplo GDPR."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"Si uso el móvil personal o una app no aprobada para resolver más rápido, saco datos del cliente fuera de todo control."</em></p><div class="sp-warn">Se cubre con la <b>Pieza 2</b>. Normativa: MiFID II, GDPR, Ley 10/2010 (PBC/FT), EU AI Act.</div>', en: '<ul><li><em>"If the assistant recommends an investment product, I give advice without suitability (MiFID II)."</em></li><li><em>"If I query unmasked customer data, I breach GDPR."</em></li></ul><h4 class="sp-sh">Shadow AI</h4><p><em>"If I use a personal phone or an unapproved app to go faster, I move customer data out of all control."</em></p><div class="sp-warn">Covered by <b>Piece 2</b>. Regulation: MiFID II, GDPR, AML law, EU AI Act.</div>'}},
      {h: {es: 'Remediación (Solo.io)', en: 'Remediation (Solo.io)'}, body: {es: "<table class='sp-t'><tr><th>Riesgo</th><th>Componente</th><th>Mecanismo</th></tr><tr><td>Asesoramiento sin gate</td><td class='sp-c'>agentgateway+HITL</td><td>disclosure; inversión → derivar a humano</td></tr><tr><td>PII de cliente</td><td class='sp-c'>agentgateway</td><td>enmascarado del core en request/response</td></tr><tr><td>App no aprobada</td><td class='sp-c'>agentregistry</td><td>sin registro no hay acceso</td></tr></table><h4>Identidad</h4><p>SPIFFE + OIDC + OBO con el rol del empleado.</p><h4>Políticas</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code>.</p>", en: "<table class='sp-t'><tr><th>Risk</th><th>Component</th><th>Mechanism</th></tr><tr><td>Ungated advice</td><td class='sp-c'>agentgateway+HITL</td><td>disclosure; investment → hand off to human</td></tr><tr><td>Customer PII</td><td class='sp-c'>agentgateway</td><td>core masking on request/response</td></tr><tr><td>Unapproved app</td><td class='sp-c'>agentregistry</td><td>no registration, no access</td></tr></table><h4>Identity</h4><p>SPIFFE + OIDC + OBO with the employee role.</p><h4>Policies</h4><p><code>AgentgatewayPolicy</code> + <code>AuthorizationPolicy</code>.</p>"}},
    ],
  },
];
